import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {useRouter} from 'next/router'
import {useToggle} from '../local-npm/simple-daily-hooks'

export default function Home() {

  const [value, toggleValue] = useToggle()

  const router = useRouter()

  let handleClick = () => {

    console.log("Placing your order...")
    router.push('/shop') // navigating by pushing

  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Hello - Next JS 🤓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next Hello 😀
        </h1>
        <button onClick={handleClick}>
          Place Order 🥗
        </button>
        <Link href="/users">
              <button>😁Users</button>
        </Link>
        <Link href="/posts">
              <button>📗 Posts</button>
        </Link>
        <button onClick={toggleValue}>Toggle:{`${value}`}</button>


      </main>
    </div>
  )
}
